[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake"]

[phases.build]
cmds = ["npm install", "cd server && npm install", "cd ../client && npm install && npm run build"]

[start]
cmd = "cd server && node index.js"
